config/routes.rb
Rails.application.routes.draw do
  # get 'static_pages/top'
  root 'static_pages#top'
  get '/course', to:'static_pages#course'
  get '/gallery', to:'static_pages#gallery'
  get '/access', to:'static_pages#access'
  get '/contact', to:'static_pages#contact'
  get '/admin_top', to:'admin#admin_top', as:'admin_top'
  get '/add_work', to:'admin#add_work', as:'add_work'
  get '/admin_access', to:'admin#access', as:'admin_access'
  post '/access_save', to:'admin#access_save'
  post '/send_contact', to:'static_pages#send_contact'
  get '/show_contacts', to:'static_pages#show_contacts', as:'show_contacts'
  post '/work_save', to:'admin#work_save', as:'work_save'
  get '/course_management', to:'admin#course_management', as:'course_management'
  post '/course_change', to:'admin#course_change', as:'course_change'
  get '/bridal_management', to:'admin#bridal_management', as:'hoge'
  post '/bridal_change', to:'admin#bridal_change', as:'bridal_change'
  get '/certifieds_management', to:'admin#certifieds_management', as:'certifieds_management'
  post'/certifieds_change',to:'admin#certifieds_change',as:'certifieds_change'
  get '/admin_notice' , to:'admin#notice' ,as:'notice'
  post '/notice_save', to:'admin#notice_save', as:'notice_save'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/access.rb
class Access < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bridal.rb
class Bridal < ApplicationRecord
end

app/models/certified.rb
class Certified < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/notice.rb
class Notice < ApplicationRecord
end

app/models/one_day.rb
class OneDay < ApplicationRecord
end

app/models/work.rb
class Work < ApplicationRecord
    mount_uploader :image, ImageUploader
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    def admin_top
    end
    def access
        @access = Access.new
    end
    def access_save
        #入力ページに入力した値を取得
        puts params[:zipcode]
        puts params[:address]
        puts params[:tel]
        puts params[:mail]
        #入力した情報をデーターベースに保存
        @access = Access.new(zipcode:params[:zipcode],address:params[:address],tel:params[:tel],mail:params[:mail])
        @access.save
        redirect_to admin_access_path
    end
    def add_work
        @work = Work.new
    end 
    def work_save
        @work = Work.new(work_params)
        @work.save
        redirect_to add_work_path
    end
    def course_management
        #既にあるデータをデータベースから持ってくる。
        @now = OneDay.find_by_id(1)
     #   @one_day = OneDay.new
    end
    def course_change
        # viewでname="number"と書いてある入力ボックスに入力された値を取得。
        @number = params[:number]
        # viewでname="price_one"と書いてある入力ボックスに入力された値を取得。
        @price_one = params[:price_one]
        # viewでname="price_pair"と書いてある入力ボックスに入力された値を取得。
        @price_pair = params[:price_pair]
        # viewでname="comment"と書いてある入力ボックスに入力された値を取得。
        @comment = params[:comment]
        #エラー処理
        #@numberが入力されていなければエラー
        if @number == ''
            flash[:error] = '人数が入力されていません'
            redirect_to course_management_path
        elsif @price_one == ''
            flash[:error] = 'ひとり価格が入力されていません'
            redirect_to course_management_path
        elsif @price_pair == ''
            flash[:error] = 'ペア価格が入力されていません'
            redirect_to course_management_path
        elsif @comment == ''
            flash[:error] = 'コメントが入力されていません'
            redirect_to course_management_path
        else
            # p 'ここを見ろ'
            # p @number
            #既にあるデータをデータベースから持ってくる。
            @one_day = OneDay.find_by_id(1)
            # p @one_day.number
            # p @one_day.comment
            #入力された値によって更新する
            @one_day.update(number:@number, price_one:@price_one, price_pair:@price_pair, comment:@comment)
            flash[:sucess] = 'コース情報を変更しました'
            redirect_to admin_top_path
        end
    end
    #bridalsの内容を更新する画面を表示する
    def bridal_management 
        #modelを使ってdbからデータを持ってくる。
        #bridalsテーブルからIDが１データの塊を持ってくる。それをhogeと名付ける。
        @hoge = Bridal.find_by_id(1)
        #hogeから日時情報を引き出して表示
        p 'ここを見ろ'
        p @hoge.id
        p @hoge.datetime
        p @hoge.entry_price
        p @hoge.four_times_price
        p @hoge.comment
    end
    #ブライダル・アートフラワーコースの情報を変更する
    def bridal_change
        p 'ここを通過'
        #入力された値を取得する。
        datetime = params[:datetime]
        p datetime
        entry_price = params[:entry_price]
        p entry_price
        four_times_price = params[:four_times_price]
        p four_times_price
        comment = params[:comment]
        p comment
        #入力された値を元にテーブルの情報を書き換える
        #まず、bridals tableからID１の情報の塊を抜き出す
        @hoge = Bridal.find_by_id(1)
        #@hogeの値を更新する
        @hoge.update(datetime:datetime,entry_price:entry_price,four_times_price:four_times_price,comment:comment)
        redirect_to admin_top_path
    end
    #資格取得講座管理
    def certifieds_management
        #modelを使ってdbからデータを持ってくる。
        @hogehoge = Certified.find_by_id(1)
        p @hogehoge.id
        p @hogehoge.datetime
        p @hogehoge.four_times_price
        p @hogehoge.comment
    end
    def certifieds_change
        p 'ここを通過'
        datetime = params[:datetime]
        p datetime
        four_times_price = params[:four_times_price]
        p four_times_price
        comment = params[:comment]
        p comment
        #db値を変更する
        #①今あるデータを持ってくる
        @hogehoge = Certified.find_by_id(1)
        #②入力された値(93,95,97の３つの値)で、@hogehogeのカラム情報を上書きする
        @hogehoge.update(datetime:datetime,four_times_price:four_times_price,comment:comment)
        #情報が無事に変更されたメッセージを保存する
        flash[:sucess] = '資格取得情報を変更しました'
        redirect_to admin_top_path
    end
    #ストロングパラメーター
    def work_params
      params.require(:work).permit(:name, :image)
    end
    def notice_params
         params.require(:notice).permit(:publication_date, :notice)
    end 
    #お知らせの登録
    def notice
        @notice=Notice.new
    end
    def notice_save
        @notice = Notice.new(notice_params)
        @notice.save
      redirect_to admin_top_path
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top
    @notices = Notice.all
  end
  def course
    @one_days = OneDay.all
    @bridals = Bridal.all
    @certifieds = Certified.all
  end
  def gallery
    @works = Work.all
  end
  def access
    @accesses = Access.all
  end
  def contact
  end
  
  def send_contact
    puts '送信されました'
     #入力ページに入力した値を取得
        puts params[:name]
        puts params[:email]
        puts params[:interest]
        puts params[:category]
        puts params[:questionnaire]
        puts params[:detail]
        #入力した情報をデーターベースに保存
        @contact = Contact.new(name:params[:name],mail:params[:email],course:params[:interest],contact:params[:category],know:params[:questionnaire],comment:params[:detail])
        @contact.save
        #@access = Access.new(zipcode:params[:zipcode],address:params[:address],tel:params[:tel],mail:params[:mail])
        #@access.save
        #redirect_to admin_access_path
  end
  def show_contacts
    @contacts = Contact.all
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/access.html.erb
<h1>住所入力</h1>
<!--<form method = 'post'>-->
<%= form_tag('/access_save') do %>
    <div>
        郵便番号<input type="text" name="zipcode">
    </div>
     <div>
        住所<input type="text" name="address">
    </div>
     <div>
        電話番号<input type="text" name="tel">
    </div>
     <div>
        メールアドレス<input type="text" name="mail">
    </div>
    <input type="submit" value="登録">
<!--</form>-->
<% end %>
<h2><%= link_to '管理者TOP', admin_top_path %></h2>

app/views/admin/add_work.html.erb
<h1>生徒作品管理ページ</h1>
<h2>生徒作品新規アップロード</h2>
<!-- <form>
    <p>名前:<input type="text"></p>
    <p>作品画像:<input type="file"></p>
    <p><input type="submit" value="作品追加"></p>
</form> -->
<%= form_for @work, url: work_save_path do |f| %>
    <div>
        <%= f.label :name, "お名前" %>
        <%= f.text_field :name %>
    </div>
    <div>
        <%= f.label :image, "作品画像" %>
        <%= f.file_field :image %>
    </div>
    <div>
        <%= f.submit "作品追加" %>
    </div>
<% end %>
<h2><%= link_to '管理者TOPへ', admin_top_path %></h2>

app/views/admin/admin_top.html.erb
<h1>管理者TOP</h1>
<p class = "sucess"><%= flash[:sucess] %></p>
<h2><%= link_to '問い合わせ管理', admin_access_path %></h2>
<h2><%= link_to '生徒作品管理', add_work_path %></h2>
<h2><%= link_to 'コース情報管理', course_management_path %></h2>
<h2><%= link_to 'ブライダル・アートフラワーコース管理', hoge_path %></h2>
<h2><%= link_to '資格取得講座管理', certifieds_management_path %></h2>
<h2><%= link_to 'お知らせ登録', notice_path %></h2>

app/views/admin/bridal_management.html.erb
<h1>ブライダル・アートフラワーコース管理</h1>
<%= form_tag('/bridal_change') do %>
    <div>
        日時：<input type = "text" value= "<%= @hoge.datetime %>" name = "datetime">
    </div>
    <div>
    　　入会金 : <input type = "text" value= "<%= @hoge.entry_price %>" name = "entry_price">
    </div>
    <div>
    　　月謝4回 : <input type = "text" value= "<%= @hoge.four_times_price %>" name = "four_times_price">
    </div>
    <div>
        持ち物 : <input type = "text" value= "<%= @hoge.comment %>" name = "comment">
    </div>
    <div>
      <input type = "submit" value = "変更">
    </div>
<% end %>
<h2><%= link_to '管理者TOPへ', admin_top_path %></h2>

app/views/admin/certifieds_management.html.erb
<h1>資格獲得講座</h1>
<%= form_tag('/certifieds_change') do %>
    <div>
        日時：<input type = "text" value= "<%= @hogehoge.datetime %>" name = "datetime">
    </div>
    <div>
    　　月謝4回 : <input type = "text" value= "<%= @hogehoge.four_times_price %>" name = "four_times_price">
    </div>
    <div>
        持ち物 : <input type = "text" value= "<%= @hogehoge.comment %>" name = "comment">
    </div>
    <div>
      <input type = "submit" value = "変更">
    </div>
<% end %>
<h2><%= link_to '管理者TOPへ', admin_top_path %></h2>

app/views/admin/course_management.html.erb
<h1>コース情報管理</h1>
<p class = "error"><%= flash[:error] %></p>
<%= form_tag('/course_change') do %>
    <div>
        人数：<input type = "text" value= "<%= @now.number %>" name = "number">
    </div>
    <div>
    　　ひとり価格 : <input type = "text" value= "<%= @now.price_one %>" name = "price_one">
    </div>
    <div>
        ペア価格 : <input type = "text" value= "<%= @now.price_pair %>" name = "price_pair">
    </div>
    <div>
        コメント : <input type = "text" value= "<%= @now.comment %>" name = "comment">
    </div>
    <div>
      <input type = "submit" value = "変更">
    </div>
<% end %>
<h2><%= link_to '管理者TOPへ', admin_top_path %></h2>

app/views/admin/notice.html.erb
<%= form_for @notice, url: notice_save_path do |f| %>
<div>
        <%= f.label :publication_date, "掲載日" %>
        <%= f.text_field :publication_date %>
    </div>
    <div>
        <%= f.label :notice, "お知らせ内容" %>
        <%= f.text_field :notice %>
    </div>
     <div>
        <%= f.submit "新規登録" %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlowerShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--<h1>テスト</h1>-->
    <%= yield %>
  </body>
</html>

app/views/static_pages/access.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<title>アクセス｜フラワーアレンジメント教室 Bloom</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="Bloomへのアクセスはこちら。東京都千代田区○○町1-2-3 フラワーアレンジメント教室Bloom">
<link rel="stylesheet" href="css/style.css">
<link rel="stylesheet" href="css/font-awesome.min.css">
<link rel="shortcut icon" href="favicon.ico">
<link rel="apple-touch-icon" href="webclip152.png">
</head>
<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v2.5&appId=643231655816289";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

  <!--ヘッダー-->
  <header>
    <h1><a href="index.html"><%= image_tag 'logo.png' %></a></h1>
    <div id="header_contact"><a href="contact.html"><%= image_tag 'btn_contact.jpg' %></a></div>
    <nav id="global_navi">
     <ul>
        <!--<li class="current"><a href="index.html">HOME</a></li>-->
        <li class="current"><%= link_to 'HOME', root_path %></li>
        <!--<li><a href="course.html">講座案内</a></li>-->
        <li><%= link_to '講座案内', '/course' %></li>
        <!--<li><a href="gallery.html">ギャラリー</a></li>-->
        <li><%= link_to 'ギャラリー', '/gallery' %></li>
        <li><a href="access.html">アクセス</a></li>
        <li><a href="contact.html">お問い合わせ</a></li>
      </ul>
    </nav>
  </header>
  <!--/ヘッダー-->

  <!--wrapper-->
  <div id="wrapper">
    <!--メイン-->
    <div id="main">
      <div id="breadcrumb">
        <ol>
          <li><a href="index.html">HOME</a></li>
          <li>アクセス</li>
        </ol>
      </div>
      <article>
        <h1>アクセス</h1>
        <section>
          <h2>Bloomへのアクセス</h2>
          <section>
            <h3>住所</h3>
            <% @accesses.each do |access| %>
            <p>〒<%= access.zipcode %></p>
            <p><%= access.address %></p>
            <p><%= access.tel %></p>
            <p><%= access.mail %></p>
            <% end %>
            <!--<p>〒000-0000<br>
            ○○県○○市○○町1-2-3 フラワーアレンジメント教室ブルーム </p> -->
          </section>
          <section>
            <h3>地図</h3>
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3240.299426535222!2d139.75812346553133!3d35.69424858686488!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x60188c104b9196e1%3A0x3c4200a784a9cd13!2z44CSMTAxLTAwNTEg5p2x5Lqs6YO95Y2D5Luj55Sw5Yy656We55Sw56We5L-d55S677yR5LiB55uu77yR77yQ77yVIOelnuS_neeUuuS4ieS6leODk-ODq-ODh-OCo-ODs-OCsA!5e0!3m2!1sja!2sjp!4v1456301503312" width="730" height="600" frameborder="0" style="border:0" allowfullscreen></iframe>
          </section>
        </section>
      </article>
      <div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>
    </div>
    <!--/メイン-->

    <!--サイド-->
    <aside id="sidebar">
      <section id="side_banner">
        <h2>関連リンク</h2>
        <ul>
          <li><a href="#" target="_blank"><%= image_tag 'banner01.jpg' %></a>
          </li>
          <li><a href="https://www.facebook.com/" target="_blank"><%= image_tag 'banner02.jpg' %></a></li>
        </ul>
      </section>
      <section id="side_contact">
        <h2>ご予約・お問い合わせ</h2>
        <address><i class="fa fa-phone"></i>052-232-8229</address>
        <p>受付時間 9:00〜18:00</p>
        <p><a href="contact.html" class="contact_button">お問い合わせフォーム</a></p>
      </section>
      <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://bloom.ne.jp" data-text="あなただけのフラワーアレンジメント教室Bloom">Tweet</a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
    </aside>
    <!--/サイド-->
  </div>
  <!--/wrapper-->

  <!--フッター-->
  <footer>
    <div id="footer_nav">
      <ul>
        <li><a href="index.html">HOME</a></li>
        <li><a href="course.html">講座案内</a></li>
        <li><a href="gallery.html">ギャラリー</a></li>
        <li><a href="access.html">アクセス</a></li>
        <li><a href="contact.html">お問い合わせ</a></li>
        <li><a href="policy.html">プライバシーポリシー</a></li>
      </ul>
    </div>
    <small>&copy; 2015 Bloom.</small>
  </footer>
  <!--/フッター-->

</body>
</html>

app/views/static_pages/contact.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<title>お問い合わせ｜フラワーアレンジメント教室 Bloom</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="Bloomへのご質問やお問い合わせは、お電話もしくはお問い合わせフォームにて受け付けております。お気軽にお問い合わせください。TEL：052-232-8229">
<link rel="stylesheet" href="css/style.css">
<link rel="stylesheet" href="css/font-awesome.min.css">
<link rel="shortcut icon" href="favicon.ico">
<link rel="apple-touch-icon" href="webclip152.png">
</head>
<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v2.5&appId=643231655816289";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

  <!--ヘッダー-->
  <header>
    <h1><a href="index.html"><%= image_tag'logo.png' %></a></h1>
    <div id="header_contact"><a href="contact.html"><%= image_tag 'btn_contact.jpg' %></a></div>
    <nav id="global_navi">
      <ul>
        <!--<li class="current"><a href="index.html">HOME</a></li>-->
        <li class="current"><%= link_to 'HOME', root_path %></li>
        <!--<li><a href="course.html">講座案内</a></li>-->
        <li><%= link_to '講座案内', '/course' %></li>
        <!--<li><a href="gallery.html">ギャラリー</a></li>-->
        <li><%= link_to 'ギャラリー', '/gallery' %></li>
        <li><a href="access.html">アクセス</a></li>
        <li><a href="contact.html">お問い合わせ</a></li>
      </ul>
    </nav>
  </header>
  <!--/ヘッダー-->

  <!--wrapper-->
  <div id="wrapper">
    <!--メイン-->
    <div id="main">
      <div id="breadcrumb">
        <ol>
          <li><a href="index.html">HOME</a></li>
          <li>お問い合わせ</li>
        </ol>
      </div>
      <article>        
        <h1>お問い合わせ</h1>
        <p class="lead">お気軽にお問い合わせください</p>
        <p>下記メールフォームをご記入いただき、「送信する」ボタンを押してください。</p>
        <p>「<span class="must">※</span>」は必須項目です。</p>
        <section>
          <h2>お問い合わせフォーム</h2>
          <%= form_tag('/send_contact') do %>
            <dl>
              <dt>お名前 <span class="must">※</span></dt>
              <dd><input type="text" name="name" id="name" required></dd>
              <dt>メールアドレス <span class="must">※</span></dt>
              <dd><input type="email" name="email" id="email" required></dd>
              <dt>興味のある講座</dt>
              <dd>
                <select name="interest" id="interest">
                <option value="1day体験教室">1day体験教室</option>
                <option value="ブライダル・アートフラワー教室">ブライダル・アートフラワー教室</option>
                <option value="資格取得講座">資格取得講座</option>
                </select>
              </dd>
              <dt>お問い合せ種別</dt>
              <dd>
                <label><input type="checkbox" name="category" id="category1" value="講座申し込み">講座申し込み</label>
                <label><input type="checkbox" name="category" id="category2" value="資料請求">資料請求</label>
                <label><input type="checkbox" name="category" id="category3" value="その他問い合わせ">その他問い合わせ</label>
              </dd>
              <dt>Bloomを知ったきっかけ</dt>
              <dd>
                <label><input type="radio" name="questionnaire" id="questionnaire1" value="口コミ">口コミ</label>
                <label><input type="radio" name="questionnaire" id="questionnaire2" value="検索エンジンから">検索エンジンから</label>
                <label><input type="radio" name="questionnaire" id="questionnaire3" value="その他">その他</label>
              </dd>
              <dt>お問い合せ内容</dt>
              <dd>
                <textarea name="detail" id="detail"></textarea>
              </dd>
            </dl>
            <p id="submit_button_cover">
              <input type="submit" id="submit_button" value="送信する">
            </p>
          <% end %>
        </section>
      </article>
      <div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>
    </div>
    <!--/メイン-->

    <!--サイド-->
    <aside id="sidebar">
      <section id="side_banner">
        <h2>関連リンク</h2>
        <ul>
          <li><a href="#" target="_blank"><%= image_tag 'banner01.jpg' %></a></li>
          <li><a href="https://www.facebook.com/" target="_blank"><%= image_tag 'banner02.jpg' %></a></li>
        </ul>
      </section>
      <section id="side_contact">
        <h2>ご予約・お問い合わせ</h2>
        <address><i class="fa fa-phone"></i>052-232-8229</address>
        <p>受付時間 9:00〜18:00</p>
        <p><a href="contact.html" class="contact_button">お問い合わせフォーム</a></p>
      </section>
      <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://bloom.ne.jp" data-text="あなただけのフラワーアレンジメント教室Bloom">Tweet</a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
    </aside>
    <!--/サイド-->
  </div>
  <!--/wrapper-->

  <!--フッター-->
  <footer>
    <div id="footer_nav">
      <ul>
        <li><a href="index.html">HOME</a></li>
        <li><a href="course.html">講座案内</a></li>
        <li><a href="gallery.html">ギャラリー</a></li>
        <li><a href="access.html">アクセス</a></li>
        <li><a href="contact.html">お問い合わせ</a></li>
        <li><a href="policy.html">プライバシーポリシー</a></li>
      </ul>
    </div>
    <small>&copy; 2015 Bloom.</small>
  </footer>
  <!--/フッター-->
  
</body>
</html>

app/views/static_pages/send_contact.html.erb
お問い合わせ完了しました。
<%= link_to 'HOMEへ', root_path %>
<%= link_to 'お問い合わせ一覧へ', show_contacts_path %>

app/views/static_pages/show_contacts.html.erb
<% @contacts.each do |contact| %>
<p>
    <%= contact.name %>
    <%= contact.mail %>
    <%= contact.course %>
    <%= contact.contact %>
    <%= contact.know %>
    <%= contact.comment %>
</p>
<% end %>
<%= link_to 'HOMEへ', root_path %>